# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/GhostMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class GhostMessage(genpy.Message):
  _md5sum = "ff33699472448776499294d59ada2106"
  _type = "morai_msgs/GhostMessage"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int16 option_geometry
byte option_dynamics

float64 offset_east
float64 offset_north
float64 offset_height

float64 pos_x
float64 pos_y
float64 pos_z

float64 heading

float64 velocity

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','option_geometry','option_dynamics','offset_east','offset_north','offset_height','pos_x','pos_y','pos_z','heading','velocity']
  _slot_types = ['std_msgs/Header','int16','byte','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,option_geometry,option_dynamics,offset_east,offset_north,offset_height,pos_x,pos_y,pos_z,heading,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GhostMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.option_geometry is None:
        self.option_geometry = 0
      if self.option_dynamics is None:
        self.option_dynamics = 0
      if self.offset_east is None:
        self.offset_east = 0.
      if self.offset_north is None:
        self.offset_north = 0.
      if self.offset_height is None:
        self.offset_height = 0.
      if self.pos_x is None:
        self.pos_x = 0.
      if self.pos_y is None:
        self.pos_y = 0.
      if self.pos_z is None:
        self.pos_z = 0.
      if self.heading is None:
        self.heading = 0.
      if self.velocity is None:
        self.velocity = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.option_geometry = 0
      self.option_dynamics = 0
      self.offset_east = 0.
      self.offset_north = 0.
      self.offset_height = 0.
      self.pos_x = 0.
      self.pos_y = 0.
      self.pos_z = 0.
      self.heading = 0.
      self.velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hb8d().pack(_x.option_geometry, _x.option_dynamics, _x.offset_east, _x.offset_north, _x.offset_height, _x.pos_x, _x.pos_y, _x.pos_z, _x.heading, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 67
      (_x.option_geometry, _x.option_dynamics, _x.offset_east, _x.offset_north, _x.offset_height, _x.pos_x, _x.pos_y, _x.pos_z, _x.heading, _x.velocity,) = _get_struct_hb8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hb8d().pack(_x.option_geometry, _x.option_dynamics, _x.offset_east, _x.offset_north, _x.offset_height, _x.pos_x, _x.pos_y, _x.pos_z, _x.heading, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 67
      (_x.option_geometry, _x.option_dynamics, _x.offset_east, _x.offset_north, _x.offset_height, _x.pos_x, _x.pos_y, _x.pos_z, _x.heading, _x.velocity,) = _get_struct_hb8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_hb8d = None
def _get_struct_hb8d():
    global _struct_hb8d
    if _struct_hb8d is None:
        _struct_hb8d = struct.Struct("<hb8d")
    return _struct_hb8d
