// Generated by gencpp from file morai_msgs/FactoryAddress.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_FACTORYADDRESS_H
#define MORAI_MSGS_MESSAGE_FACTORYADDRESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct FactoryAddress_
{
  typedef FactoryAddress_<ContainerAllocator> Type;

  FactoryAddress_()
    : factory_addr_row(0)
    , factory_addr_col(0)
    , mission_index(0)  {
    }
  FactoryAddress_(const ContainerAllocator& _alloc)
    : factory_addr_row(0)
    , factory_addr_col(0)
    , mission_index(0)  {
  (void)_alloc;
    }



   typedef int32_t _factory_addr_row_type;
  _factory_addr_row_type factory_addr_row;

   typedef int32_t _factory_addr_col_type;
  _factory_addr_col_type factory_addr_col;

   typedef int32_t _mission_index_type;
  _mission_index_type mission_index;





  typedef boost::shared_ptr< ::morai_msgs::FactoryAddress_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::FactoryAddress_<ContainerAllocator> const> ConstPtr;

}; // struct FactoryAddress_

typedef ::morai_msgs::FactoryAddress_<std::allocator<void> > FactoryAddress;

typedef boost::shared_ptr< ::morai_msgs::FactoryAddress > FactoryAddressPtr;
typedef boost::shared_ptr< ::morai_msgs::FactoryAddress const> FactoryAddressConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::FactoryAddress_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::FactoryAddress_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::FactoryAddress_<ContainerAllocator1> & lhs, const ::morai_msgs::FactoryAddress_<ContainerAllocator2> & rhs)
{
  return lhs.factory_addr_row == rhs.factory_addr_row &&
    lhs.factory_addr_col == rhs.factory_addr_col &&
    lhs.mission_index == rhs.mission_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::FactoryAddress_<ContainerAllocator1> & lhs, const ::morai_msgs::FactoryAddress_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::FactoryAddress_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::FactoryAddress_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::FactoryAddress_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a5097aee45ce9c14e33f6cc877af060";
  }

  static const char* value(const ::morai_msgs::FactoryAddress_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a5097aee45ce9c1ULL;
  static const uint64_t static_value2 = 0x4e33f6cc877af060ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/FactoryAddress";
  }

  static const char* value(const ::morai_msgs::FactoryAddress_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 factory_addr_row\n"
"int32 factory_addr_col\n"
"\n"
"int32 mission_index\n"
;
  }

  static const char* value(const ::morai_msgs::FactoryAddress_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.factory_addr_row);
      stream.next(m.factory_addr_col);
      stream.next(m.mission_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactoryAddress_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::FactoryAddress_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::FactoryAddress_<ContainerAllocator>& v)
  {
    s << indent << "factory_addr_row: ";
    Printer<int32_t>::stream(s, indent + "  ", v.factory_addr_row);
    s << indent << "factory_addr_col: ";
    Printer<int32_t>::stream(s, indent + "  ", v.factory_addr_col);
    s << indent << "mission_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mission_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_FACTORYADDRESS_H
