// Generated by gencpp from file morai_msgs/GetTrafficLightStatus.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_GETTRAFFICLIGHTSTATUS_H
#define MORAI_MSGS_MESSAGE_GETTRAFFICLIGHTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct GetTrafficLightStatus_
{
  typedef GetTrafficLightStatus_<ContainerAllocator> Type;

  GetTrafficLightStatus_()
    : header()
    , isAutoMode(false)
    , trafficLightIndex()
    , trafficLightType(0)
    , trafficLightStatus(0)  {
    }
  GetTrafficLightStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isAutoMode(false)
    , trafficLightIndex(_alloc)
    , trafficLightType(0)
    , trafficLightStatus(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isAutoMode_type;
  _isAutoMode_type isAutoMode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _trafficLightIndex_type;
  _trafficLightIndex_type trafficLightIndex;

   typedef int16_t _trafficLightType_type;
  _trafficLightType_type trafficLightType;

   typedef int16_t _trafficLightStatus_type;
  _trafficLightStatus_type trafficLightStatus;





  typedef boost::shared_ptr< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GetTrafficLightStatus_

typedef ::morai_msgs::GetTrafficLightStatus_<std::allocator<void> > GetTrafficLightStatus;

typedef boost::shared_ptr< ::morai_msgs::GetTrafficLightStatus > GetTrafficLightStatusPtr;
typedef boost::shared_ptr< ::morai_msgs::GetTrafficLightStatus const> GetTrafficLightStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isAutoMode == rhs.isAutoMode &&
    lhs.trafficLightIndex == rhs.trafficLightIndex &&
    lhs.trafficLightType == rhs.trafficLightType &&
    lhs.trafficLightStatus == rhs.trafficLightStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1abbbbcdf4cbe9669bd9ad6c73568c1d";
  }

  static const char* value(const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1abbbbcdf4cbe966ULL;
  static const uint64_t static_value2 = 0x9bd9ad6c73568c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/GetTrafficLightStatus";
  }

  static const char* value(const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"bool isAutoMode\n"
"string trafficLightIndex\n"
"int16 trafficLightType\n"
"int16 trafficLightStatus\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isAutoMode);
      stream.next(m.trafficLightIndex);
      stream.next(m.trafficLightType);
      stream.next(m.trafficLightStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTrafficLightStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::GetTrafficLightStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isAutoMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isAutoMode);
    s << indent << "trafficLightIndex: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.trafficLightIndex);
    s << indent << "trafficLightType: ";
    Printer<int16_t>::stream(s, indent + "  ", v.trafficLightType);
    s << indent << "trafficLightStatus: ";
    Printer<int16_t>::stream(s, indent + "  ", v.trafficLightStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_GETTRAFFICLIGHTSTATUS_H
