// Generated by gencpp from file morai_msgs/MgeoNodeList.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MGEONODELIST_H
#define MORAI_MSGS_MESSAGE_MGEONODELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <morai_msgs/MgeoNode.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MgeoNodeList_
{
  typedef MgeoNodeList_<ContainerAllocator> Type;

  MgeoNodeList_()
    : header()
    , node_list()  {
    }
  MgeoNodeList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , node_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::morai_msgs::MgeoNode_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::morai_msgs::MgeoNode_<ContainerAllocator> >::other >  _node_list_type;
  _node_list_type node_list;





  typedef boost::shared_ptr< ::morai_msgs::MgeoNodeList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MgeoNodeList_<ContainerAllocator> const> ConstPtr;

}; // struct MgeoNodeList_

typedef ::morai_msgs::MgeoNodeList_<std::allocator<void> > MgeoNodeList;

typedef boost::shared_ptr< ::morai_msgs::MgeoNodeList > MgeoNodeListPtr;
typedef boost::shared_ptr< ::morai_msgs::MgeoNodeList const> MgeoNodeListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MgeoNodeList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MgeoNodeList_<ContainerAllocator1> & lhs, const ::morai_msgs::MgeoNodeList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.node_list == rhs.node_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MgeoNodeList_<ContainerAllocator1> & lhs, const ::morai_msgs::MgeoNodeList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MgeoNodeList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MgeoNodeList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MgeoNodeList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ae9b44b45a36f86376fd00317de8521";
  }

  static const char* value(const ::morai_msgs::MgeoNodeList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ae9b44b45a36f86ULL;
  static const uint64_t static_value2 = 0x376fd00317de8521ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MgeoNodeList";
  }

  static const char* value(const ::morai_msgs::MgeoNodeList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"MgeoNode[] node_list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MgeoNode\n"
"string node_id\n"
"float32 cost\n"
"float32 time_cost\n"
"\n"
"int32 node_type #if the node type is -1, unuse this data\n"
"\n"
"string[] to_link_id\n"
"string[] from_link_id\n"
"\n"
"geometry_msgs/Pose node\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::morai_msgs::MgeoNodeList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.node_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MgeoNodeList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MgeoNodeList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "node_list[]" << std::endl;
    for (size_t i = 0; i < v.node_list.size(); ++i)
    {
      s << indent << "  node_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::MgeoNode_<ContainerAllocator> >::stream(s, indent + "    ", v.node_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MGEONODELIST_H
