// Generated by gencpp from file morai_msgs/Mgeo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MGEO_H
#define MORAI_MSGS_MESSAGE_MGEO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <morai_msgs/MgeoNodeList.h>
#include <morai_msgs/MgeoLinkList.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct Mgeo_
{
  typedef Mgeo_<ContainerAllocator> Type;

  Mgeo_()
    : map_name()
    , local_offset()
    , lane_change_link_include(false)
    , node_list()
    , link_list()  {
    }
  Mgeo_(const ContainerAllocator& _alloc)
    : map_name(_alloc)
    , local_offset(_alloc)
    , lane_change_link_include(false)
    , node_list(_alloc)
    , link_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_name_type;
  _map_name_type map_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _local_offset_type;
  _local_offset_type local_offset;

   typedef uint8_t _lane_change_link_include_type;
  _lane_change_link_include_type lane_change_link_include;

   typedef  ::morai_msgs::MgeoNodeList_<ContainerAllocator>  _node_list_type;
  _node_list_type node_list;

   typedef  ::morai_msgs::MgeoLinkList_<ContainerAllocator>  _link_list_type;
  _link_list_type link_list;





  typedef boost::shared_ptr< ::morai_msgs::Mgeo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::Mgeo_<ContainerAllocator> const> ConstPtr;

}; // struct Mgeo_

typedef ::morai_msgs::Mgeo_<std::allocator<void> > Mgeo;

typedef boost::shared_ptr< ::morai_msgs::Mgeo > MgeoPtr;
typedef boost::shared_ptr< ::morai_msgs::Mgeo const> MgeoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::Mgeo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::Mgeo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::Mgeo_<ContainerAllocator1> & lhs, const ::morai_msgs::Mgeo_<ContainerAllocator2> & rhs)
{
  return lhs.map_name == rhs.map_name &&
    lhs.local_offset == rhs.local_offset &&
    lhs.lane_change_link_include == rhs.lane_change_link_include &&
    lhs.node_list == rhs.node_list &&
    lhs.link_list == rhs.link_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::Mgeo_<ContainerAllocator1> & lhs, const ::morai_msgs::Mgeo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Mgeo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Mgeo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Mgeo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Mgeo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Mgeo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Mgeo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::Mgeo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffa290ab15496480ebcd89bbc9fb80e1";
  }

  static const char* value(const ::morai_msgs::Mgeo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffa290ab15496480ULL;
  static const uint64_t static_value2 = 0xebcd89bbc9fb80e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::Mgeo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/Mgeo";
  }

  static const char* value(const ::morai_msgs::Mgeo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::Mgeo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_name\n"
"\n"
"geometry_msgs/Pose local_offset\n"
"bool lane_change_link_include\n"
"\n"
"MgeoNodeList node_list\n"
"MgeoLinkList link_list\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MgeoNodeList\n"
"Header header\n"
"\n"
"MgeoNode[] node_list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MgeoNode\n"
"string node_id\n"
"float32 cost\n"
"float32 time_cost\n"
"\n"
"int32 node_type #if the node type is -1, unuse this data\n"
"\n"
"string[] to_link_id\n"
"string[] from_link_id\n"
"\n"
"geometry_msgs/Pose node\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MgeoLinkList\n"
"Header header\n"
"\n"
"MgeoLink[] link_list\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MgeoLink\n"
"string link_id\n"
"float32 cost\n"
"float32 time_cost\n"
"\n"
"uint32 lane_idx\n"
"string left_link_id\n"
"string right_link_id\n"
"\n"
"string to_node_id\n"
"string from_node_id\n"
"\n"
"int32 link_type\n"
"uint32 length\n"
"uint32 speed\n"
"\n"
"# 0: not change, 1: left, 2: right\n"
"int32 change_lane\n"
"# change target link id\n"
"string change_link_id\n"
"\n"
"# link_type enum\n"
"int32 LINK_NONE=0\n"
"int32 LINK_TOLLGATE_NORMAL=3\n"
"int32 LINK_BUS_LANE=4\n"
"int32 LINK_REVERSIBLE_LANE=5\n"
"int32 LINK_REGULAR_LANE=6\n"
"\n"
"# change_lane enum\n"
"int32 CHANGE_NONE=0\n"
"int32 CHANGE_LEFT=1\n"
"int32 CHANGE_RIGHT=2\n"
"\n"
"geometry_msgs/Pose[] waypoints\n"
;
  }

  static const char* value(const ::morai_msgs::Mgeo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::Mgeo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_name);
      stream.next(m.local_offset);
      stream.next(m.lane_change_link_include);
      stream.next(m.node_list);
      stream.next(m.link_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mgeo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::Mgeo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::Mgeo_<ContainerAllocator>& v)
  {
    s << indent << "map_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_name);
    s << indent << "local_offset: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.local_offset);
    s << indent << "lane_change_link_include: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lane_change_link_include);
    s << indent << "node_list: ";
    s << std::endl;
    Printer< ::morai_msgs::MgeoNodeList_<ContainerAllocator> >::stream(s, indent + "  ", v.node_list);
    s << indent << "link_list: ";
    s << std::endl;
    Printer< ::morai_msgs::MgeoLinkList_<ContainerAllocator> >::stream(s, indent + "  ", v.link_list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MGEO_H
