// Generated by gencpp from file morai_msgs/MoraiTimestamp.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAITIMESTAMP_H
#define MORAI_MSGS_MESSAGE_MORAITIMESTAMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiTimestamp_
{
  typedef MoraiTimestamp_<ContainerAllocator> Type;

  MoraiTimestamp_()
    : msec(0.0)
    , dateTime()  {
    }
  MoraiTimestamp_(const ContainerAllocator& _alloc)
    : msec(0.0)
    , dateTime(_alloc)  {
  (void)_alloc;
    }



   typedef double _msec_type;
  _msec_type msec;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dateTime_type;
  _dateTime_type dateTime;





  typedef boost::shared_ptr< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiTimestamp_

typedef ::morai_msgs::MoraiTimestamp_<std::allocator<void> > MoraiTimestamp;

typedef boost::shared_ptr< ::morai_msgs::MoraiTimestamp > MoraiTimestampPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiTimestamp const> MoraiTimestampConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiTimestamp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiTimestamp_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTimestamp_<ContainerAllocator2> & rhs)
{
  return lhs.msec == rhs.msec &&
    lhs.dateTime == rhs.dateTime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiTimestamp_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTimestamp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c518394d21e3fbb8021d76f4d57e5d2";
  }

  static const char* value(const ::morai_msgs::MoraiTimestamp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c518394d21e3fbbULL;
  static const uint64_t static_value2 = 0x8021d76f4d57e5d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiTimestamp";
  }

  static const char* value(const ::morai_msgs::MoraiTimestamp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 msec\n"
"string dateTime\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiTimestamp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msec);
      stream.next(m.dateTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiTimestamp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiTimestamp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiTimestamp_<ContainerAllocator>& v)
  {
    s << indent << "msec: ";
    Printer<double>::stream(s, indent + "  ", v.msec);
    s << indent << "dateTime: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dateTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAITIMESTAMP_H
