// Generated by gencpp from file morai_msgs/ReplayInfo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_REPLAYINFO_H
#define MORAI_MSGS_MESSAGE_REPLAYINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct ReplayInfo_
{
  typedef ReplayInfo_<ContainerAllocator> Type;

  ReplayInfo_()
    : header()
    , ego_acc(0.0)
    , ego_brake(0.0)
    , ego_steer(0.0)
    , ego_orientation_x(0.0)
    , ego_orientation_y(0.0)
    , ego_orientation_z(0.0)
    , ego_orientation_w(0.0)
    , ego_linearAcceleration_x(0.0)
    , ego_linearAcceleration_y(0.0)
    , ego_linearAcceleration_z(0.0)
    , ego_AngularVelocity_x(0.0)
    , ego_AngularVelocity_y(0.0)
    , ego_AngularVelocity_z(0.0)
    , num_of_objects(0)
    , object_type()
    , object_id()
    , pose_x()
    , pose_y()
    , pose_z()
    , heading()
    , size_x()
    , size_y()
    , size_z()
    , velocity()  {
    }
  ReplayInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ego_acc(0.0)
    , ego_brake(0.0)
    , ego_steer(0.0)
    , ego_orientation_x(0.0)
    , ego_orientation_y(0.0)
    , ego_orientation_z(0.0)
    , ego_orientation_w(0.0)
    , ego_linearAcceleration_x(0.0)
    , ego_linearAcceleration_y(0.0)
    , ego_linearAcceleration_z(0.0)
    , ego_AngularVelocity_x(0.0)
    , ego_AngularVelocity_y(0.0)
    , ego_AngularVelocity_z(0.0)
    , num_of_objects(0)
    , object_type(_alloc)
    , object_id(_alloc)
    , pose_x(_alloc)
    , pose_y(_alloc)
    , pose_z(_alloc)
    , heading(_alloc)
    , size_x(_alloc)
    , size_y(_alloc)
    , size_z(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _ego_acc_type;
  _ego_acc_type ego_acc;

   typedef double _ego_brake_type;
  _ego_brake_type ego_brake;

   typedef double _ego_steer_type;
  _ego_steer_type ego_steer;

   typedef double _ego_orientation_x_type;
  _ego_orientation_x_type ego_orientation_x;

   typedef double _ego_orientation_y_type;
  _ego_orientation_y_type ego_orientation_y;

   typedef double _ego_orientation_z_type;
  _ego_orientation_z_type ego_orientation_z;

   typedef double _ego_orientation_w_type;
  _ego_orientation_w_type ego_orientation_w;

   typedef double _ego_linearAcceleration_x_type;
  _ego_linearAcceleration_x_type ego_linearAcceleration_x;

   typedef double _ego_linearAcceleration_y_type;
  _ego_linearAcceleration_y_type ego_linearAcceleration_y;

   typedef double _ego_linearAcceleration_z_type;
  _ego_linearAcceleration_z_type ego_linearAcceleration_z;

   typedef double _ego_AngularVelocity_x_type;
  _ego_AngularVelocity_x_type ego_AngularVelocity_x;

   typedef double _ego_AngularVelocity_y_type;
  _ego_AngularVelocity_y_type ego_AngularVelocity_y;

   typedef double _ego_AngularVelocity_z_type;
  _ego_AngularVelocity_z_type ego_AngularVelocity_z;

   typedef int32_t _num_of_objects_type;
  _num_of_objects_type num_of_objects;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _object_type_type;
  _object_type_type object_type;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _object_id_type;
  _object_id_type object_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_x_type;
  _pose_x_type pose_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_y_type;
  _pose_y_type pose_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_z_type;
  _pose_z_type pose_z;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _heading_type;
  _heading_type heading;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _size_x_type;
  _size_x_type size_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _size_y_type;
  _size_y_type size_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _size_z_type;
  _size_z_type size_z;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::morai_msgs::ReplayInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::ReplayInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ReplayInfo_

typedef ::morai_msgs::ReplayInfo_<std::allocator<void> > ReplayInfo;

typedef boost::shared_ptr< ::morai_msgs::ReplayInfo > ReplayInfoPtr;
typedef boost::shared_ptr< ::morai_msgs::ReplayInfo const> ReplayInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::ReplayInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::ReplayInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::ReplayInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ego_acc == rhs.ego_acc &&
    lhs.ego_brake == rhs.ego_brake &&
    lhs.ego_steer == rhs.ego_steer &&
    lhs.ego_orientation_x == rhs.ego_orientation_x &&
    lhs.ego_orientation_y == rhs.ego_orientation_y &&
    lhs.ego_orientation_z == rhs.ego_orientation_z &&
    lhs.ego_orientation_w == rhs.ego_orientation_w &&
    lhs.ego_linearAcceleration_x == rhs.ego_linearAcceleration_x &&
    lhs.ego_linearAcceleration_y == rhs.ego_linearAcceleration_y &&
    lhs.ego_linearAcceleration_z == rhs.ego_linearAcceleration_z &&
    lhs.ego_AngularVelocity_x == rhs.ego_AngularVelocity_x &&
    lhs.ego_AngularVelocity_y == rhs.ego_AngularVelocity_y &&
    lhs.ego_AngularVelocity_z == rhs.ego_AngularVelocity_z &&
    lhs.num_of_objects == rhs.num_of_objects &&
    lhs.object_type == rhs.object_type &&
    lhs.object_id == rhs.object_id &&
    lhs.pose_x == rhs.pose_x &&
    lhs.pose_y == rhs.pose_y &&
    lhs.pose_z == rhs.pose_z &&
    lhs.heading == rhs.heading &&
    lhs.size_x == rhs.size_x &&
    lhs.size_y == rhs.size_y &&
    lhs.size_z == rhs.size_z &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::ReplayInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::ReplayInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5461824bc0fed3d006858ffb04fc7b18";
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5461824bc0fed3d0ULL;
  static const uint64_t static_value2 = 0x06858ffb04fc7b18ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/ReplayInfo";
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 ego_acc\n"
"float64 ego_brake\n"
"float64 ego_steer\n"
"\n"
"float64 ego_orientation_x\n"
"float64 ego_orientation_y\n"
"float64 ego_orientation_z\n"
"float64 ego_orientation_w\n"
"\n"
"float64 ego_linearAcceleration_x\n"
"float64 ego_linearAcceleration_y\n"
"float64 ego_linearAcceleration_z\n"
"\n"
"float64 ego_AngularVelocity_x\n"
"float64 ego_AngularVelocity_y\n"
"float64 ego_AngularVelocity_z\n"
"\n"
"int32 num_of_objects\n"
"int16[] object_type\n"
"\n"
"int32[] object_id\n"
"\n"
"float64[] pose_x\n"
"float64[] pose_y\n"
"float64[] pose_z\n"
"\n"
"float64[] heading\n"
"\n"
"float64[] size_x\n"
"float64[] size_y\n"
"float64[] size_z\n"
"\n"
"float64[] velocity\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ego_acc);
      stream.next(m.ego_brake);
      stream.next(m.ego_steer);
      stream.next(m.ego_orientation_x);
      stream.next(m.ego_orientation_y);
      stream.next(m.ego_orientation_z);
      stream.next(m.ego_orientation_w);
      stream.next(m.ego_linearAcceleration_x);
      stream.next(m.ego_linearAcceleration_y);
      stream.next(m.ego_linearAcceleration_z);
      stream.next(m.ego_AngularVelocity_x);
      stream.next(m.ego_AngularVelocity_y);
      stream.next(m.ego_AngularVelocity_z);
      stream.next(m.num_of_objects);
      stream.next(m.object_type);
      stream.next(m.object_id);
      stream.next(m.pose_x);
      stream.next(m.pose_y);
      stream.next(m.pose_z);
      stream.next(m.heading);
      stream.next(m.size_x);
      stream.next(m.size_y);
      stream.next(m.size_z);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReplayInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::ReplayInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ego_acc: ";
    Printer<double>::stream(s, indent + "  ", v.ego_acc);
    s << indent << "ego_brake: ";
    Printer<double>::stream(s, indent + "  ", v.ego_brake);
    s << indent << "ego_steer: ";
    Printer<double>::stream(s, indent + "  ", v.ego_steer);
    s << indent << "ego_orientation_x: ";
    Printer<double>::stream(s, indent + "  ", v.ego_orientation_x);
    s << indent << "ego_orientation_y: ";
    Printer<double>::stream(s, indent + "  ", v.ego_orientation_y);
    s << indent << "ego_orientation_z: ";
    Printer<double>::stream(s, indent + "  ", v.ego_orientation_z);
    s << indent << "ego_orientation_w: ";
    Printer<double>::stream(s, indent + "  ", v.ego_orientation_w);
    s << indent << "ego_linearAcceleration_x: ";
    Printer<double>::stream(s, indent + "  ", v.ego_linearAcceleration_x);
    s << indent << "ego_linearAcceleration_y: ";
    Printer<double>::stream(s, indent + "  ", v.ego_linearAcceleration_y);
    s << indent << "ego_linearAcceleration_z: ";
    Printer<double>::stream(s, indent + "  ", v.ego_linearAcceleration_z);
    s << indent << "ego_AngularVelocity_x: ";
    Printer<double>::stream(s, indent + "  ", v.ego_AngularVelocity_x);
    s << indent << "ego_AngularVelocity_y: ";
    Printer<double>::stream(s, indent + "  ", v.ego_AngularVelocity_y);
    s << indent << "ego_AngularVelocity_z: ";
    Printer<double>::stream(s, indent + "  ", v.ego_AngularVelocity_z);
    s << indent << "num_of_objects: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_objects);
    s << indent << "object_type[]" << std::endl;
    for (size_t i = 0; i < v.object_type.size(); ++i)
    {
      s << indent << "  object_type[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.object_type[i]);
    }
    s << indent << "object_id[]" << std::endl;
    for (size_t i = 0; i < v.object_id.size(); ++i)
    {
      s << indent << "  object_id[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.object_id[i]);
    }
    s << indent << "pose_x[]" << std::endl;
    for (size_t i = 0; i < v.pose_x.size(); ++i)
    {
      s << indent << "  pose_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_x[i]);
    }
    s << indent << "pose_y[]" << std::endl;
    for (size_t i = 0; i < v.pose_y.size(); ++i)
    {
      s << indent << "  pose_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_y[i]);
    }
    s << indent << "pose_z[]" << std::endl;
    for (size_t i = 0; i < v.pose_z.size(); ++i)
    {
      s << indent << "  pose_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_z[i]);
    }
    s << indent << "heading[]" << std::endl;
    for (size_t i = 0; i < v.heading.size(); ++i)
    {
      s << indent << "  heading[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.heading[i]);
    }
    s << indent << "size_x[]" << std::endl;
    for (size_t i = 0; i < v.size_x.size(); ++i)
    {
      s << indent << "  size_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.size_x[i]);
    }
    s << indent << "size_y[]" << std::endl;
    for (size_t i = 0; i < v.size_y.size(); ++i)
    {
      s << indent << "  size_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.size_y[i]);
    }
    s << indent << "size_z[]" << std::endl;
    for (size_t i = 0; i < v.size_z.size(); ++i)
    {
      s << indent << "  size_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.size_z[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_REPLAYINFO_H
