// Generated by gencpp from file morai_msgs/SVehicleStatus.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SVEHICLESTATUS_H
#define MORAI_MSGS_MESSAGE_SVEHICLESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct SVehicleStatus_
{
  typedef SVehicleStatus_<ContainerAllocator> Type;

  SVehicleStatus_()
    : header()
    , vehicle_num(0)
    , pose_x()
    , pose_y()
    , pose_z()
    , heading()
    , velocity()  {
    }
  SVehicleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_num(0)
    , pose_x(_alloc)
    , pose_y(_alloc)
    , pose_z(_alloc)
    , heading(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _vehicle_num_type;
  _vehicle_num_type vehicle_num;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_x_type;
  _pose_x_type pose_x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_y_type;
  _pose_y_type pose_y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _pose_z_type;
  _pose_z_type pose_z;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _heading_type;
  _heading_type heading;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::morai_msgs::SVehicleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::SVehicleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SVehicleStatus_

typedef ::morai_msgs::SVehicleStatus_<std::allocator<void> > SVehicleStatus;

typedef boost::shared_ptr< ::morai_msgs::SVehicleStatus > SVehicleStatusPtr;
typedef boost::shared_ptr< ::morai_msgs::SVehicleStatus const> SVehicleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::SVehicleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::SVehicleStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::SVehicleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_num == rhs.vehicle_num &&
    lhs.pose_x == rhs.pose_x &&
    lhs.pose_y == rhs.pose_y &&
    lhs.pose_z == rhs.pose_z &&
    lhs.heading == rhs.heading &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::SVehicleStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::SVehicleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SVehicleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SVehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SVehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5761b53523289f5262479d10b4bbf7c";
  }

  static const char* value(const ::morai_msgs::SVehicleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5761b53523289f5ULL;
  static const uint64_t static_value2 = 0x262479d10b4bbf7cULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/SVehicleStatus";
  }

  static const char* value(const ::morai_msgs::SVehicleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 vehicle_num\n"
"float64[] pose_x\n"
"float64[] pose_y\n"
"float64[] pose_z\n"
"float64[] heading\n"
"float64[] velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::SVehicleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_num);
      stream.next(m.pose_x);
      stream.next(m.pose_y);
      stream.next(m.pose_z);
      stream.next(m.heading);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SVehicleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::SVehicleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::SVehicleStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vehicle_num);
    s << indent << "pose_x[]" << std::endl;
    for (size_t i = 0; i < v.pose_x.size(); ++i)
    {
      s << indent << "  pose_x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_x[i]);
    }
    s << indent << "pose_y[]" << std::endl;
    for (size_t i = 0; i < v.pose_y.size(); ++i)
    {
      s << indent << "  pose_y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_y[i]);
    }
    s << indent << "pose_z[]" << std::endl;
    for (size_t i = 0; i < v.pose_z.size(); ++i)
    {
      s << indent << "  pose_z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_z[i]);
    }
    s << indent << "heading[]" << std::endl;
    for (size_t i = 0; i < v.heading.size(); ++i)
    {
      s << indent << "  heading[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.heading[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SVEHICLESTATUS_H
