// Generated by gencpp from file morai_msgs/VehicleSpec.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VEHICLESPEC_H
#define MORAI_MSGS_MESSAGE_VEHICLESPEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct VehicleSpec_
{
  typedef VehicleSpec_<ContainerAllocator> Type;

  VehicleSpec_()
    : size()
    , wheel_base(0.0)
    , max_steering(0.0)  {
    }
  VehicleSpec_(const ContainerAllocator& _alloc)
    : size(_alloc)
    , wheel_base(0.0)
    , max_steering(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef float _wheel_base_type;
  _wheel_base_type wheel_base;

   typedef double _max_steering_type;
  _max_steering_type max_steering;





  typedef boost::shared_ptr< ::morai_msgs::VehicleSpec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VehicleSpec_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpec_

typedef ::morai_msgs::VehicleSpec_<std::allocator<void> > VehicleSpec;

typedef boost::shared_ptr< ::morai_msgs::VehicleSpec > VehicleSpecPtr;
typedef boost::shared_ptr< ::morai_msgs::VehicleSpec const> VehicleSpecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VehicleSpec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VehicleSpec_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VehicleSpec_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpec_<ContainerAllocator2> & rhs)
{
  return lhs.size == rhs.size &&
    lhs.wheel_base == rhs.wheel_base &&
    lhs.max_steering == rhs.max_steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VehicleSpec_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpec_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "625d357e6d273edab34b02324c79c461";
  }

  static const char* value(const ::morai_msgs::VehicleSpec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x625d357e6d273edaULL;
  static const uint64_t static_value2 = 0xb34b02324c79c461ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VehicleSpec";
  }

  static const char* value(const ::morai_msgs::VehicleSpec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 size\n"
"float32 wheel_base\n"
"float64 max_steering\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::VehicleSpec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.wheel_base);
      stream.next(m.max_steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VehicleSpec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VehicleSpec_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "wheel_base: ";
    Printer<float>::stream(s, indent + "  ", v.wheel_base);
    s << indent << "max_steering: ";
    Printer<double>::stream(s, indent + "  ", v.max_steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VEHICLESPEC_H
