// Generated by gencpp from file morai_msgs/VelPlot.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VELPLOT_H
#define MORAI_MSGS_MESSAGE_VELPLOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct VelPlot_
{
  typedef VelPlot_<ContainerAllocator> Type;

  VelPlot_()
    : target_vel(0.0)
    , current_vel(0.0)  {
    }
  VelPlot_(const ContainerAllocator& _alloc)
    : target_vel(0.0)
    , current_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _target_vel_type;
  _target_vel_type target_vel;

   typedef double _current_vel_type;
  _current_vel_type current_vel;





  typedef boost::shared_ptr< ::morai_msgs::VelPlot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VelPlot_<ContainerAllocator> const> ConstPtr;

}; // struct VelPlot_

typedef ::morai_msgs::VelPlot_<std::allocator<void> > VelPlot;

typedef boost::shared_ptr< ::morai_msgs::VelPlot > VelPlotPtr;
typedef boost::shared_ptr< ::morai_msgs::VelPlot const> VelPlotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VelPlot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VelPlot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VelPlot_<ContainerAllocator1> & lhs, const ::morai_msgs::VelPlot_<ContainerAllocator2> & rhs)
{
  return lhs.target_vel == rhs.target_vel &&
    lhs.current_vel == rhs.current_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VelPlot_<ContainerAllocator1> & lhs, const ::morai_msgs::VelPlot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VelPlot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VelPlot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VelPlot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VelPlot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VelPlot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VelPlot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VelPlot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a3e50e6c7d121a90051a8b33f0ba8d";
  }

  static const char* value(const ::morai_msgs::VelPlot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a3e50e6c7d121aULL;
  static const uint64_t static_value2 = 0x90051a8b33f0ba8dULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VelPlot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VelPlot";
  }

  static const char* value(const ::morai_msgs::VelPlot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VelPlot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 target_vel\n"
"float64 current_vel\n"
;
  }

  static const char* value(const ::morai_msgs::VelPlot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VelPlot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_vel);
      stream.next(m.current_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelPlot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VelPlot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VelPlot_<ContainerAllocator>& v)
  {
    s << indent << "target_vel: ";
    Printer<double>::stream(s, indent + "  ", v.target_vel);
    s << indent << "current_vel: ";
    Printer<double>::stream(s, indent + "  ", v.current_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VELPLOT_H
