(cl:in-package morai_msgs-msg)
(cl:export '(LINK_ID-VAL
          LINK_ID
          COST-VAL
          COST
          TIME_COST-VAL
          TIME_COST
          LANE_IDX-VAL
          LANE_IDX
          LEFT_LINK_ID-VAL
          LEFT_LINK_ID
          RIGHT_LINK_ID-VAL
          RIGHT_LINK_ID
          TO_NODE_ID-VAL
          TO_NODE_ID
          FROM_NODE_ID-VAL
          FROM_NODE_ID
          LINK_TYPE-VAL
          LINK_TYPE
          LENGTH-VAL
          LENGTH
          SPEED-VAL
          SPEED
          CHANGE_LANE-VAL
          CHANGE_LANE
          CHANGE_LINK_ID-VAL
          CHANGE_LINK_ID
          WAYPOINTS-VAL
          WAYPOINTS
))