(cl:in-package morai_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          EGO_ACC-VAL
          EGO_ACC
          EGO_BRAKE-VAL
          EGO_BRAKE
          EGO_STEER-VAL
          EGO_STEER
          EGO_ORIENTATION_X-VAL
          EGO_ORIENTATION_X
          EGO_ORIENTATION_Y-VAL
          EGO_ORIENTATION_Y
          EGO_ORIENTATION_Z-VAL
          EGO_ORIENTATION_Z
          EGO_ORIENTATION_W-VAL
          EGO_ORIENTATION_W
          EGO_LINEARACCELERATION_X-VAL
          EGO_LINEARACCELERATION_X
          EGO_LINEARACCELERATION_Y-VAL
          EGO_LINEARACCELERATION_Y
          EGO_LINEARACCELERATION_Z-VAL
          EGO_LINEARACCELERATION_Z
          EGO_ANGULARVELOCITY_X-VAL
          EGO_ANGULARVELOCITY_X
          EGO_ANGULARVELOCITY_Y-VAL
          EGO_ANGULARVELOCITY_Y
          EGO_ANGULARVELOCITY_Z-VAL
          EGO_ANGULARVELOCITY_Z
          NUM_OF_OBJECTS-VAL
          NUM_OF_OBJECTS
          OBJECT_TYPE-VAL
          OBJECT_TYPE
          OBJECT_ID-VAL
          OBJECT_ID
          POSE_X-VAL
          POSE_X
          POSE_Y-VAL
          POSE_Y
          POSE_Z-VAL
          POSE_Z
          HEADING-VAL
          HEADING
          SIZE_X-VAL
          SIZE_X
          SIZE_Y-VAL
          SIZE_Y
          SIZE_Z-VAL
          SIZE_Z
          VELOCITY-VAL
          VELOCITY
))