(cl:in-package morai_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTERSECTION_INDEX-VAL
          INTERSECTION_INDEX
          INTERSECTION_STATUS-VAL
          INTERSECTION_STATUS
          INTERSECTION_STATUS_TIME-VAL
          INTERSECTION_STATUS_TIME
          TRAFFIC_LIGHT_INDEX-VAL
          TRAFFIC_LIGHT_INDEX
          TRAFFIC_LIGHT_STATUS-VAL
          TRAFFIC_LIGHT_STATUS
          TRAFFIC_LIGHT_NEXT_STATUS-VAL
          TRAFFIC_LIGHT_NEXT_STATUS
))